// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgcti.Infrastructure.Persistence;

#nullable disable

namespace Sgcti.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SgctiDbContext))]
    [Migration("20261007081614_AgregarBitacora")]
    partial class AgregarBitacora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgcti.Core.Entities.BitacoraActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalistaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EquipoIntervenido")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("Estado");

                    b.ToTable("BitacoraActividades", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Consumible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiasAntelacionPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ModeloCompatible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Consumibles", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.HistorialConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumibleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImpresoraId")
                        .HasColumnType("integer");

                    b.Property<int>("PaginasImpresas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsumibleId");

                    b.HasIndex("FechaCambio");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("HistorialConsumo", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Impresora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertaStockCritico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ComputadorasVinculadas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ComunidadSnmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ConsumibleTonerId")
                        .HasColumnType("integer");

                    b.Property<int>("ContadorColor")
                        .HasColumnType("integer");

                    b.Property<int>("ContadorMonocromo")
                        .HasColumnType("integer");

                    b.Property<int>("ContadorTotalPaginas")
                        .HasColumnType("integer");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("DiasEstimadosAgotamientoTonner")
                        .HasColumnType("integer");

                    b.Property<int>("DiasEstimadosMantenimiento")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoPing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaEstimadaAgotamientoTonner")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NivelTonnerAmarillo")
                        .HasColumnType("integer");

                    b.Property<int?>("NivelTonnerCian")
                        .HasColumnType("integer");

                    b.Property<int?>("NivelTonnerMagenta")
                        .HasColumnType("integer");

                    b.Property<int>("NivelTonnerNegro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PaginasDesdeUltimoMantenimiento")
                        .HasColumnType("integer");

                    b.Property<double>("PromedioPaginasDiario")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("PromedioTonnerDiario")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("RutaManual")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UltimoMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertaStockCritico");

                    b.HasIndex("ConsumibleTonerId");

                    b.HasIndex("Departamento");

                    b.HasIndex("DiasEstimadosAgotamientoTonner");

                    b.HasIndex("DiasEstimadosMantenimiento");

                    b.HasIndex("Ip")
                        .IsUnique();

                    b.HasIndex("NivelTonnerNegro");

                    b.ToTable("Impresoras", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.MetricaRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DispositivoIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatenciaMS")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("PaquetesPerdidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoIP");

                    b.HasIndex("FechaHora");

                    b.ToTable("MetricasRed", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.RegistroConsumoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Consumo")
                        .HasColumnType("integer");

                    b.Property<int>("Contador")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImpresoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("RegistrosConsumoDiario", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Suministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("Tipo");

                    b.ToTable("Suministros", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SLAHoras")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacion");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Sgcti.Core.Entities.HistorialConsumo", b =>
                {
                    b.HasOne("Sgcti.Core.Entities.Consumible", "Consumible")
                        .WithMany("HistorialConsumo")
                        .HasForeignKey("ConsumibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sgcti.Core.Entities.Impresora", "Impresora")
                        .WithMany("HistorialConsumo")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumible");

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Impresora", b =>
                {
                    b.HasOne("Sgcti.Core.Entities.Consumible", "ConsumibleToner")
                        .WithMany()
                        .HasForeignKey("ConsumibleTonerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConsumibleToner");
                });

            modelBuilder.Entity("Sgcti.Core.Entities.RegistroConsumoDiario", b =>
                {
                    b.HasOne("Sgcti.Core.Entities.Impresora", "Impresora")
                        .WithMany("RegistrosConsumoDiario")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Consumible", b =>
                {
                    b.Navigation("HistorialConsumo");
                });

            modelBuilder.Entity("Sgcti.Core.Entities.Impresora", b =>
                {
                    b.Navigation("HistorialConsumo");

                    b.Navigation("RegistrosConsumoDiario");
                });
#pragma warning restore 612, 618
        }
    }
}
